name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create files
        run: echo "Created by job" > test.txt
      
      - name: Show files
        run: cat test.txt

  isolation-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Try to read test.txt
        run: cat test.txt